### ISSUE TITLE
Roadmap: 0.1 release

### ISSUE THREAD

**Issue by dhardy** [dhardy/kas#14]
A priority list for making a somewhat usable release:

- [x] text processing #4, #13: at least add clipboard integration ~and ability to move edit position left/right~
- [ ] graphics #6: visible separators
- [x] dynamic layouts #5, #2
- [x] custom widgets #16, #3
- [ ] layout memory & adjustment handles #3, #2
- [x] check-boxes #2: visible indicator needed
- [ ] radio boxes #2: linking of multiple widgets needed
- [x] scrollable regions #2
- [ ] multi-window example with synchronised data

**Comment by sombrastudios** [comment]
I really like this roadmap.
However, you might keep kas as simple and possible and move the implementation of widgets into another crate. 

This might encourage developers to contribute to both crates and other than that spawn a whole ecosystem of widgets. (or at least encourage this)

Just a thought. Keep up the great work

**Comment by dhardy** [comment]
Hey, thanks for the comment; I believe you're the first to do so on this repo!

Moving widget implementations into a separate crate should be easy given that these are already in a dedicated sub-module, however KAS is not yet close to API stability, thus co-versioning of the crates would be required. Given that, is there any point (yet)?

**Comment by sombrastudios** [comment]
Glad I've commented then, this is an honor for KAS surely will have an interesting future.

I mainly commented because I've felt this would be a great opportunity to leverage rusts ecosystem and have a less 'monolithic' (probably using this word slightly wrong) approach at Crate design.
Though I myself don't have experience publishing own crates yet.

API instability is a good argument against this. Having two different crates would slow down development and might even discourage putting the effort in. 
In question is if one can refactor widgets when the 1.0 release comes, without causing too much chaos in (then) existing projects.

I think one can mark functions as `depreciated`, which then might be the right move.

looking forward to seeing how kas will grow

**Comment by dhardy** [comment]
With the `rand*` libs we went with a multi-crate approach; it does have certain advantages (separation of APIs, modular with-respect-to replaceable implementations, stabilising components independently). There is definitely reason to do this with some of KAS too, e.g. the `kas-wgpu` component should be replaceable (perhaps for better integration on some platforms, or integration within a game), and the layout code may become a re-usable component (in other GUI libs). I'm less sure about the widgets though; these are quite tightly integrated with the core library.

**Comment by dhardy** [comment]
In the interests of an earlier release, I am considering postponing non-trivial items (e.g. custom widgets and dynamic layouts).

**Comment by dhardy** [comment]
Custom widgets will now be in this release. In fact there should be nothing special about the included widgets, aside from a limited and specialised drawing API (to be improved in a later release). This would allow an external widget crate as @sombrastudios suggested although I'm still not convinced such a micro-crate approach is valuable.

Dynamic widgets may be included too if the recent trait redesign does not get in the way. Some other items on the list might be dropped due to time limits.

After this release I will make some effort to facilitate community contribution and likely switch to making changes via PR.

**Comment by dhardy** [comment]
Pre-release [0.1.0-pre-1](https://crates.io/crates/kas/0.1.0-pre.1) is out.

At this point the main blockers to a 0.1 release is testing. The remaining items above likely will not make 0.1.0.

**Comment by dhardy** [comment]
Version [0.1.0 is published](https://crates.io/crates/kas/0.1.0).

The remaining items are not considered worth blocking the release on. The multi-window example should already be possible (although event-triggered creation is not: #28).
